add in directory batch processing
use -d to pass in the directory to convert all the files in

diff --git a/v4e b/v4e
--- a/v4e
+++ b/v4e
@@ -5,26 +5,40 @@
 VERSION="1.0.0"
 VSCALE="480:-1"
 
-help() {
+helpText() {
     echo "Video 4 Everybody Conversion script v$VERSION"
     echo ""
     echo "Convert the passed in video file to various formats for the web"
     echo "OPTIONS:"
-    echo "-i input file (required)"
+    echo "-d input directory (required if input file is omitted)"
+    echo "-i input file (required if directory is omitted)"
     echo "-o output file (required)"
     echo "-v video scaling (defaults to 480:-1 to preserver aspect ratio)"
     exit 0
 }
 
+convertFile() {
+    echo "Creating .mp4 version"
+    ffmpeg -i "$1" -codec:v libx264 -preset slow -profile:v main -crf 20 -codec:a aac -ab 128k -vf scale="$VSCALE" "$2".mp4
+    echo "Creating .ogv version"
+    ffmpeg -i "$1" -codec:v libtheora -q:v 6 -codec:a libvorbis -ab 128k -vf scale="$VSCALE" "$2".ogv
+    echo "Creating .webm version"
+    ffmpeg -i "$1" -codec:v libvpx -q:v 6 -codec:a libvorbis -ab 128k -vf scale="$VSCALE" "$2".webm
+    echo "done"
+}
+
 if [ $# == 0 ]; then
-    help
+    helpText
 fi
 
-while getopts "hi:o:v:" opt; do
+while getopts "hd:i:o:v:" opt; do
     case $opt in
         h)
-            help
+            helpText
             exit 0
+            ;;
+        d)
+            DIRECTORY="$OPTARG" >&2
             ;;
         i)
             FILENAME="$OPTARG" >&2
@@ -46,23 +60,44 @@ while getopts "hi:o:v:" opt; do
     esac
 done
 
-if [ ! -e "$FILENAME" ]; then
-    echo "$FILENAME does not exist" >&2
+if [ -z $DIRECTORY ] && [ -z $FILENAME ]; then
+    echo "You must either pass in a filename or a directory with either -i or -d respectively" >&2
     exit 1
 fi
 
 if [ -z $OUTPUT ]; then
-    echo "please set -o with the base output file name (no extension)" >&2
+    echo "please set -o with the base output file name (no extension) if you used -i or the folder if you used -d" >&2
     exit 1
 fi
 
-echo "Processing $FILENAME"
+if [ ! -z "$FILENAME" ]; then
 
-echo "Creating .mp4 version"
-ffmpeg -i "$FILENAME" -codec:v libx264 -preset slow -profile:v main -crf 20 -codec:a aac -ab 128k -vf scale="$VSCALE" "$OUTPUT".mp4
-echo "Creating .ogv version"
-ffmpeg -i "$FILENAME" -codec:v libtheora -q:v 6 -codec:a libvorbis -ab 128k -vf scale="$VSCALE" "$OUTPUT".ogv
-echo "Creating .webm version"
-ffmpeg -i "$FILENAME" -codec:v libvpx -q:v 6 -codec:a libvorbis -ab 128k -vf scale="$VSCALE" "$OUTPUT".webm
-echo "done"
+    if [ ! -e "$FILENAME" ]; then
+        echo "$FILENAME does not exist" >&2
+        exit 1
+    fi
+
+    echo "Processing $FILENAME"
+    convertFile "$FILENAME" "$OUTPUT"
+fi
+
+if [ ! -z "$DIRECTORY" ]; then
+    if [ ! -d "$DIRECTORY" ]; then
+        echo "Source Directory $DIRECTORY does not exist" >&2
+        exit 1
+    fi
+    mkdir -p "$OUTPUT"
+    for file in "$DIRECTORY"/*
+    do
+        if [ -e "$file" ]; then
+            name=`basename "$file"`
+            name=`echo ${name} | cut -f 1 -d '.'`
+            output="$OUTPUT/$name"
+            convertFile "$file" "$output"
+        fi
+    done
+
+fi
+
+
 exit 0
